#!/bin/bash

# Build Docker Image
docker build -t meal-prepare .

# The command line above will create a docker image name 'meal-prepare'.
# Use the command docker image ls -a, to see the images in your local system.

# Run Docker Container
docker run -it -d -p 80:80 meal-prepare

# In case the port 80 is occupied you can use this
# docker run -it -d -p 8080:80 meal-prepare

# Use 'docker ps' command to view the running container or if you didn't find any container use 'docker ps -a' to view all container in any state on your machine

# Access Your Application and 'Let's Cook'
# Go on localhost:${port} and enjoy
